default:
  target: dev
  outputs:
    dev:
      type: "{{ env_var('CONNECTION_TYPE')}}"
      account: "{{ env_var('DB_HOST')}}"
      user: "{{ env_var('DB_USER')}}"
      password: "{{ env_var('DB_PASSWORD')}}"
      database: "{{ env_var('DB_NAME')}}"
      schema: "{{ env_var('DB_SCHEMA')}}"
      role: "{{ env_var('DB_ROLE')}}"
      warehouse: "COMPUTE_WH"